## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import gmaps
import requests

# Import the API key.
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

ModuleNotFoundError: No module named 'gmaps'

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("Weather_Database/WeatherPy_Database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Date
0,0,Murgab,TM,37.4966,61.9714,50.32,38,7,4.76,clear sky,2021-11-24 03:01:29
1,1,Saskylakh,RU,71.9167,114.0833,-18.29,90,49,12.03,scattered clouds,2021-11-24 03:01:29
2,2,Kapaa,US,22.0752,-159.3190,79.12,71,23,1.01,few clouds,2021-11-24 03:01:29
3,3,Vostok,RU,46.4856,135.8833,12.31,88,100,10.31,light snow,2021-11-24 03:01:29
4,4,Arraial Do Cabo,BR,-22.9661,-42.0278,71.65,89,50,8.16,scattered clouds,2021-11-24 03:01:30

In [7]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp])
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

In [3]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 70
What is the maximum temperature you would like for your trip? 95

In [4]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Date
2,2,Kapaa,US,22.0752,-159.3190,79.12,71,23,1.01,few clouds,2021-11-24 03:01:29
4,4,Arraial Do Cabo,BR,-22.9661,-42.0278,71.65,89,50,8.16,scattered clouds,2021-11-24 03:01:30
6,6,Avarua,CK,-21.2078,-159.7750,78.85,61,94,12.66,overcast clouds,2021-11-24 02:57:19
12,12,Presidencia Roque Saenz Pena,AR,-26.7852,-60.4388,73.15,70,3,1.48,clear sky,2021-11-24 03:01:32
13,13,Pemangkat,ID,1.1667,108.9667,84.16,65,100,4.07,overcast clouds,2021-11-24 03:01:32
14,14,Busselton,AU,-33.6500,115.3333,73.80,41,2,6.20,clear sky,2021-11-24 03:01:32
16,16,Basoko,CD,1.2391,23.6160,71.46,90,74,2.71,broken clouds,2021-11-24 03:01:33
23,23,Lorengau,PG,-2.0226,147.2712,80.73,84,100,15.30,moderate rain,2021-11-24 03:01:34
24,24,Jalingo,NG,8.8833,11.3667,77.31,27,73,3.02,broken clouds,2021-11-24 03:01:35
27,27,Saint-Philippe,RE,-21.3585,55.7679,78.22,65,27,7.65,scattered clouds,2021-11-24 03:01:36

In [5]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.notnull().sum()

City_ID                243
City                   243
Country                243
Lat                    243
Lng                    243
Max Temp               243
Humidity               243
Cloudiness             243
Wind Speed             243
Current Description    243
Date                   243
dtype: int64

In [6]:
preferred_cities_df.count()

City_ID                243
City                   243
Country                243
Lat                    243
Lng                    243
Max Temp               243
Humidity               243
Cloudiness             243
Wind Speed             243
Current Description    243
Date                   243
dtype: int64

In [7]:
preferred_cities_df.isnull().sum()

City_ID                0
City                   0
Country                0
Lat                    0
Lng                    0
Max Temp               0
Humidity               0
Cloudiness             0
Wind Speed             0
Current Description    0
Date                   0
dtype: int64

In [8]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
preferred_cities_df.dropna()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Date
2,2,Kapaa,US,22.0752,-159.3190,79.12,71,23,1.01,few clouds,2021-11-24 03:01:29
4,4,Arraial Do Cabo,BR,-22.9661,-42.0278,71.65,89,50,8.16,scattered clouds,2021-11-24 03:01:30
6,6,Avarua,CK,-21.2078,-159.7750,78.85,61,94,12.66,overcast clouds,2021-11-24 02:57:19
12,12,Presidencia Roque Saenz Pena,AR,-26.7852,-60.4388,73.15,70,3,1.48,clear sky,2021-11-24 03:01:32
13,13,Pemangkat,ID,1.1667,108.9667,84.16,65,100,4.07,overcast clouds,2021-11-24 03:01:32
...,...,...,...,...,...,...,...,...,...,...,...
695,695,Vieques,PR,18.4250,-65.8329,77.61,78,19,5.28,few clouds,2021-11-24 03:04:32
701,701,Katherine,AU,-14.4667,132.2667,93.52,46,100,5.75,overcast clouds,2021-11-24 03:04:33
703,703,Thinadhoo,MV,0.5333,72.9333,82.13,77,87,16.82,overcast clouds,2021-11-24 03:04:33
708,708,Mangaluru,IN,12.8667,74.8833,76.06,100,40,0.00,mist,2021-11-24 03:02:01
709,709,Bahia De Caraquez,EC,-0.6000,-80.4167,73.58,84,100,8.88,overcast clouds,2021-11-24 03:04:35

In [10]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
2,Kapaa,US,79.12,few clouds,22.0752,-159.3190,
4,Arraial Do Cabo,BR,71.65,scattered clouds,-22.9661,-42.0278,
6,Avarua,CK,78.85,overcast clouds,-21.2078,-159.7750,
12,Presidencia Roque Saenz Pena,AR,73.15,clear sky,-26.7852,-60.4388,
13,Pemangkat,ID,84.16,overcast clouds,1.1667,108.9667,
14,Busselton,AU,73.80,clear sky,-33.6500,115.3333,
16,Basoko,CD,71.46,broken clouds,1.2391,23.6160,
23,Lorengau,PG,80.73,moderate rain,-2.0226,147.2712,
24,Jalingo,NG,77.31,broken clouds,8.8833,11.3667,
27,Saint-Philippe,RE,78.22,scattered clouds,-21.3585,55.7679,

In [11]:
len(hotel_df)

243

In [12]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params = {
        "location": f"{lat},{lng}",
        "radius": 5000,
        "types" : "hotel",
        "key": g_key
    }

    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"


    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError): print("Hotel not found... skipping.")

NameError: name 'g_key' is not defined

In [9]:
# 7. Drop the rows where there is no Hotel Name.
hotel_df.head()

In [14]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
hotel_df.to_csv(output_data_file, index_label="City_ID")

In [15]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = hotel_df[["Lat", "Lng"]]

In [16]:
# 11a. Add a marker layer for each city to the map. 
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

NameError: name 'gmaps' is not defined

In [18]:
# 11b. Display the figure